// Used to store the survey inputs for the survey questions

export const surveyInputs = {
  fields: {
    gender: ["Male", "Female", "Prefer not to say", "Others"],

    ageGroup: [
      "16 to 24",
      "25 to 34",
      "35 to 44",
      "45 to 54",
      "55 to 64",
      "65 & above",
    ],

    sector: [
      "Agriculture, Forestry, and Fishing",
      "Mining and Quarrying",
      "Construction",
      "Manufacturing",
      "Utilities (Electricity, Gas, Water)",
      "Transportation and Warehousing",
      "Information Technology and Telecommunications",
      "Finance and Insurance",
      "Real Estate and Rental",
      "Professional, Scientific, and Technical Services",
      "Management and Consulting Services",
      "Education",
      "Healthcare and Social Assistance",
      "Arts, Entertainment, and Recreation",
      "Accommodation and Food Services",
      "Retail Trade",
      "Wholesale Trade",
      "Public Administration and Government",
      "Other Services (e.g., Personal Care, Repair)",
      "Nonprofit Organizations",
    ],
    education: [
      "No Formal Education",
      "Primary School",
      "Middle School",
      "Some High School, No Diploma",
      "High School",
      "GED",
      "Vocational/Technical School",
      "Some College, No Degree",
      "Associate's Degree",
      "Bachelor's Degree",
      "Professional Certification",
      "Postgraduate Diploma/Certificate",
      "Master's Degree",
      "Doctorate",
      "Doctor of Medicine (MD) or Equivalent",
      "Juris Doctor (JD)",
      "Postdoctoral Studies",
    ],
  },
  questions: [
    "I’ve been living in a safe and healthy home environment",
    "I’ve been able to enjoy a safe and healthy environment outside my home",
    "I’ve been financially secure and so have had enough income to meet my needs",
    "I’ve been doing worthwhile activities (paid/unpaid) when I’ve wanted",
    "I’ve been able to carry out what I’ve set out to do when I’ve wanted",
    "I’ve met up with family and friends and we have done things together when I’ve wanted",
    "I've been free from harassment and discrimination",
    "I’ve been able to use local services and facilities when I’ve needed",
    "I’ve felt useful when I help and support other people",
    "I’ve had my opinions taken seriously",
    "I’ve interacted with others in person when I’ve wanted",
    "I’ve interacted with others digitally, online and/or using a phone when I’ve wanted",
    "I've been involved with community groups and/or activities when I’ve wanted",
    "I’ve learnt about the world",
  ],

  options: [
    "None of the time",
    "Rarely",
    "Some of the time",
    "Often",
    "All of the time",
  ],
};
